name: Nightly Fetch

on:
  schedule:
    - cron: 0 0 * * *

  workflow_dispatch:
  
env:
  DEST_ROOT: ${{ github.workspace	}}/staging

jobs:
  fetch:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - from: bofreq
            to: ietf-ftp/bofreq
            tar: bofreq
          - from: everything-ftp/charter
            to: ietf-ftp/charter
            tar: charter
          - from: everything-ftp/conflict-reviews
            to: ietf-ftp/conflict-reviews
            tar: conflict-reviews
          - from: everything-ftp/internet-drafts
            to: ietf-ftp/internet-drafts
            tar: internet-drafts
          - from: everything-ftp/review
            to: ietf-ftp/review
            tar: review
          - from: everything-ftp/rfc
            to: ietf-ftp/rfc
            tar: rfc
          - from: everything-ftp/slides
            to: ietf-ftp/slides
            tar: slides
          - from: everything-ftp/status-changes
            to: ietf-ftp/status-changes
            tar: status-changes
          - from: everything-ftp/yang
            to: ietf-ftp/yang
            tar: yang
          - from: dev.media/floor
            to: media/floor
            tar: floor
          - from: dev.media/photo
            to: media/photo
            tar: photo
          - from: id-archive
            to: archive/id
            tar: id-archive
          - from: proceedings
            to: www6s/proceedings
            tar: proceedings

    steps:
      - uses: actions/checkout@v3

      - name: Install rsync
        run: |
          sudo apt-get update
          sudo apt-get -y install --no-install-recommends rsync
          
      - name: Fetch assets
        run: |
          dest="$DEST_ROOT/${{ matrix.to }}"
          mkdir -p "$dest"
          echo "Fetching $dest ..."
          rsync -auz rsync.ietf.org::${{ matrix.from }}/ $dest/
          echo "Building ${{ matrix.tar }}.tar.gz archive..."
          tar -czf $GITHUB_WORKSPACE/${{ matrix.tar }}.tar.gz -C $DEST_ROOT .
          
      - name: Update Release
        uses: ncipollo/release-action@v1.10.0
        with:
          allowUpdates: true
          artifacts: "${{ matrix.tar }}.tar.gz"
          omitBody: true
          omitNameDuringUpdate: true
          replacesArtifacts: true
          tag: v1
